In [ ]:
!git clone https://github.com/Yogesh-SN/cobrapy-learning.git
%cd cobrapy-learning/

In [ ]:
!pip install -r requirements.txt

In [19]:
import sys
import os

sys.path.insert(0, os.path.join(os.getcwd(), "src"))

In [20]:
from helpers import load_model
model = load_model('models/e_coli_core.xml')

In [21]:
model

In [22]:
model.summary()

In [23]:
model.objective.expression

1.0*BIOMASS_Ecoli_core_w_GAM - 1.0*BIOMASS_Ecoli_core_w_GAM_reverse_712e5

In [24]:
model.optimize()

#Growth Rate (μ) = Flux biomass


## [if normalized to 1 gDW]

In [26]:
from helpers import biomass_reaction

biomass = biomass_reaction(model)
print(biomass)

BIOMASS_Ecoli_core_w_GAM: 1.496 3pg_c + 3.7478 accoa_c + 59.81 atp_c + 0.361 e4p_c + 0.0709 f6p_c + 0.129 g3p_c + 0.205 g6p_c + 0.2557 gln__L_c + 4.9414 glu__L_c + 59.81 h2o_c + 3.547 nad_c + 13.0279 nadph_c + 1.7867 oaa_c + 0.5191 pep_c + 2.8328 pyr_c + 0.8977 r5p_c --> 59.81 adp_c + 4.1182 akg_c + 3.7478 coa_c + 59.81 h_c + 3.547 nadh_c + 13.0279 nadp_c + 59.81 pi_c

In [25]:
print(hasattr(helpers, "biomass_reaction"))

True