In [ ]:
!git clone https://github.com/Yogesh-SN/cobrapy-learning.git
%cd cobrapy-learning/

In [ ]:
!pip install -r requirements.txt

In [80]:
import sys
import os

sys.path.append(os.path.abspath("../src"))

In [81]:
from helpers import load_model
model = load_model('models/e_coli_core.xml')

In [82]:
model

In [83]:
model.summary()

In [84]:
model.objective.expression

1.0*BIOMASS_Ecoli_core_w_GAM - 1.0*BIOMASS_Ecoli_core_w_GAM_reverse_712e5

In [85]:
model.optimize()